
/* ==========================================================
   N:M Doença — Transmissor
   ========================================================== */
CREATE TABLE transmite (
  doenca        VARCHAR2(120)  NOT NULL,  -- FK -> doenca(nomecientif)
  transmissor   VARCHAR2(100)  NOT NULL,  -- FK -> transmissor(nome)

  CONSTRAINT pk_transmite PRIMARY KEY (doenca, transmissor),

  CONSTRAINT fk_transmite_doenca
    FOREIGN KEY (doenca) REFERENCES doenca (nomecientif),
  CONSTRAINT fk_transmite_transmissor
    FOREIGN KEY (transmissor) REFERENCES transmissor (nome)
);
sql
/* ==========================================================
   N:M Doença — Tratamento
   ========================================================== */
CREATE TABLE requer (
  doenca      VARCHAR2(120)  NOT NULL,  -- FK -> doenca(nomecientif)
  tratamento  VARCHAR2(150)  NOT NULL,  -- FK -> tratamento(nome)

  CONSTRAINT pk_requer PRIMARY KEY (doenca, tratamento),

  CONSTRAINT fk_requer_doenca
    FOREIGN KEY (doenca) REFERENCES doenca (nomecientif),
  CONSTRAINT fk_requer_tratamento
    FOREIGN KEY (tratamento) REFERENCES tratamento (nome)
);
/* ==========================================================
   N:M Paciente — Doença (ligação simples)
   ========================================================== */
CREATE TABLE infecta (
  paciente  NUMBER         NOT NULL,     -- FK -> paciente(idpaciente)
  doenca    VARCHAR2(120)  NOT NULL,     -- FK -> doenca(nomecientif)

  CONSTRAINT pk_infecta PRIMARY KEY (paciente, doenca),

  CONSTRAINT fk_infecta_paciente
    FOREIGN KEY (paciente) REFERENCES paciente (idpaciente),
  CONSTRAINT fk_infecta_doenca
    FOREIGN KEY (doenca)   REFERENCES doenca (nomecientif)
);
/* ==========================================================
   Agregação: ALERTA
   ========================================================== */
CREATE TABLE alerta (
  idalerta        NUMBER GENERATED BY DEFAULT AS IDENTITY,
  beneficente     CHAR(18)       NOT NULL,   -- FK -> beneficente(cnpj)
  doenca          VARCHAR2(120)  NOT NULL,   -- FK -> doenca(nomecientif)
  datainicio      DATE           NOT NULL,
  datafim         DATE,
  tipo            VARCHAR2(30),
  mensagem        VARCHAR2(4000),
  canalprincipal  VARCHAR2(50),
  prioridade      VARCHAR2(10),

  CONSTRAINT pk_alerta PRIMARY KEY (idalerta),

  -- chave secundária para unicidade operacional
  CONSTRAINT uq_alerta_bdf UNIQUE (beneficente, doenca, datainicio),

  CONSTRAINT fk_alerta_beneficente
    FOREIGN KEY (beneficente) REFERENCES beneficente (cnpj),
  CONSTRAINT fk_alerta_doenca
    FOREIGN KEY (doenca)      REFERENCES doenca (nomecientif),

  CONSTRAINT ck_alerta_datas
    CHECK (datafim IS NULL OR datafim >= datainicio)
);
/* ==========================================================
   N:M Região — Alerta
   (regiao tem PK = rede_de_saude; use o MESMO tipo da sua PK)
   ========================================================== */
CREATE TABLE abrange (
  regiao_rede_de_saude  VARCHAR2(14) NOT NULL,  -- FK -> regiao(rede_de_saude)
  idalerta              NUMBER       NOT NULL,  -- FK -> alerta(idalerta)

  CONSTRAINT pk_abrange PRIMARY KEY (regiao_rede_de_saude, idalerta),

  CONSTRAINT fk_abrange_regiao
    FOREIGN KEY (regiao_rede_de_saude) REFERENCES regiao (rede_de_saude),
  CONSTRAINT fk_abrange_alerta
    FOREIGN KEY (idalerta)             REFERENCES alerta (idalerta)
);
/* ==========================================================
   Agregação: CASO (episódio clínico)
   ========================================================== */
CREATE TABLE caso (
  idcaso      NUMBER GENERATED BY DEFAULT AS IDENTITY,
  paciente    NUMBER         NOT NULL,       -- FK -> paciente(idpaciente)
  doenca      VARCHAR2(120)  NOT NULL,       -- FK -> doenca(nomecientif)
  datainicio  DATE           NOT NULL,
  datafim     DATE,
  gravidade   VARCHAR2(20),
  obito       CHAR(1),                        -- 'S'/'N' (opcional)
  cnpj        CHAR(18)      NOT NULL,         -- FK -> orgao(cnpj)

  CONSTRAINT pk_caso PRIMARY KEY (idcaso),

  -- chave secundária para identificar o episódio
  CONSTRAINT uq_caso_ep UNIQUE (paciente, doenca, datainicio),

  CONSTRAINT fk_caso_paciente
    FOREIGN KEY (paciente) REFERENCES paciente (idpaciente),
  CONSTRAINT fk_caso_doenca
    FOREIGN KEY (doenca)   REFERENCES doenca (nomecientif),
  CONSTRAINT fk_caso_orgao
    FOREIGN KEY (cnpj)     REFERENCES orgao (cnpj),

  CONSTRAINT ck_caso_datas
    CHECK (datafim IS NULL OR datafim >= datainicio),

  CONSTRAINT ck_caso_obito
    CHECK (obito IN ('S','N') OR obito IS NULL)
);

/* índices auxiliares úteis (opcionais) */
CREATE INDEX ix_alerta_benef  ON alerta (beneficente);
CREATE INDEX ix_alerta_doenca ON alerta (doenca);

CREATE INDEX ix_caso_paciente ON caso (paciente);
CREATE INDEX ix_caso_doenca   ON caso (doenca);
CREATE INDEX ix_caso_inicio   ON caso (datainicio);
