
CREATE TABLE transmite (
  doenca        VARCHAR2(120)  NOT NULL,  -- FK -> doenca(nomecientif)
  transmissor   VARCHAR2(100)  NOT NULL,  -- FK -> transmissor(nome)

  CONSTRAINT pk_transmite PRIMARY KEY (doenca, transmissor),

  CONSTRAINT fk_transmite_doenca
    FOREIGN KEY (doenca) REFERENCES doenca (nomecientif),
  CONSTRAINT fk_transmite_transmissor
    FOREIGN KEY (transmissor) REFERENCES transmissor (nome)
);
sql

CREATE TABLE requer (
  doenca      VARCHAR2(120)  NOT NULL,  -- FK -> doenca(nomecientif)
  tratamento  VARCHAR2(150)  NOT NULL,  -- FK -> tratamento(nome)

  CONSTRAINT pk_requer PRIMARY KEY (doenca, tratamento),

  CONSTRAINT fk_requer_doenca
    FOREIGN KEY (doenca) REFERENCES doenca (nomecientif),
  CONSTRAINT fk_requer_tratamento
    FOREIGN KEY (tratamento) REFERENCES tratamento (nome)
);

CREATE TABLE infecta (
  paciente  NUMBER         NOT NULL,     -- FK -> paciente(idpaciente)
  doenca    VARCHAR2(120)  NOT NULL,     -- FK -> doenca(nomecientif)

  CONSTRAINT pk_infecta PRIMARY KEY (paciente, doenca),

  CONSTRAINT fk_infecta_paciente
    FOREIGN KEY (paciente) REFERENCES paciente (idpaciente),
  CONSTRAINT fk_infecta_doenca
    FOREIGN KEY (doenca)   REFERENCES doenca (nomecientif)
);

CREATE TABLE alerta (
  idalerta        NUMBER GENERATED BY DEFAULT AS IDENTITY,
  beneficente     CHAR(18)       NOT NULL,   -- FK -> beneficente(cnpj)
  doenca          VARCHAR2(120)  NOT NULL,   -- FK -> doenca(nomecientif)
  datainicio      DATE           NOT NULL,
  datafim         DATE,
  tipo            VARCHAR2(30),
  mensagem        VARCHAR2(4000),
  canalprincipal  VARCHAR2(50),
  prioridade      VARCHAR2(10),

  CONSTRAINT pk_alerta PRIMARY KEY (idalerta),

  -- chave secundária para unicidade operacional
  CONSTRAINT uq_alerta_bdf UNIQUE (beneficente, doenca, datainicio),

  CONSTRAINT fk_alerta_beneficente
    FOREIGN KEY (beneficente) REFERENCES beneficente (cnpj),
  CONSTRAINT fk_alerta_doenca
    FOREIGN KEY (doenca)      REFERENCES doenca (nomecientif),

  CONSTRAINT ck_alerta_datas
    CHECK (datafim IS NULL OR datafim >= datainicio)
);

CREATE TABLE abrange (
  regiao_rede_de_saude  VARCHAR2(14) NOT NULL,  -- FK -> regiao(rede_de_saude)
  idalerta              NUMBER       NOT NULL,  -- FK -> alerta(idalerta)

  CONSTRAINT pk_abrange PRIMARY KEY (regiao_rede_de_saude, idalerta),

  CONSTRAINT fk_abrange_regiao
    FOREIGN KEY (regiao_rede_de_saude) REFERENCES regiao (rede_de_saude),

  CONSTRAINT fk_abrange_alerta
    FOREIGN KEY (idalerta) REFERENCES alerta (idalerta)
);

CREATE TABLE caso (
  idcaso         NUMBER GENERATED BY DEFAULT AS IDENTITY,
  paciente       NUMBER         NOT NULL,      -- FK -> paciente(idpaciente)
  doenca         VARCHAR2(120)  NOT NULL,      -- FK -> doenca(nomecientif)
  datainicio     DATE           NOT NULL,
  datafim        DATE,
  gravidade      VARCHAR2(20),
  obito          CHAR(1),                      -- 'S'/'N' (opcional)
  rede_de_saude  VARCHAR2(14)   NOT NULL,      -- FK -> regiao(rede_de_saude)
  reincidente    CHAR(1),                      -- 'S'/'N' (opcional)

  CONSTRAINT pk_caso PRIMARY KEY (idcaso),

  -- chave secundária para identificar o episódio
  CONSTRAINT uq_caso_ep UNIQUE (paciente, doenca, datainicio),

  CONSTRAINT fk_caso_paciente
    FOREIGN KEY (paciente) REFERENCES paciente (idpaciente),

  CONSTRAINT fk_caso_doenca
    FOREIGN KEY (doenca)   REFERENCES doenca (nomecientif),

  CONSTRAINT fk_caso_rede
    FOREIGN KEY (rede_de_saude) REFERENCES regiao (rede_de_saude),

  CONSTRAINT ck_caso_datas
    CHECK (datafim IS NULL OR datafim >= datainicio),

  CONSTRAINT ck_caso_obito
    CHECK (obito IN ('S','N') OR obito IS NULL),

  CONSTRAINT ck_caso_reincidente
    CHECK (reincidente IN ('S','N') OR reincidente IS NULL)
);



